#!/bin/sh

COMMIT_MSG=$1

prefix=`head -n 1 $COMMIT_MSG | awk '{ print $1 }'`
emoji=""

case $prefix in
    "add:")
        emoji=":sparkles:"
        ;;
    "update:")
        emoji=":arrow_up_small:"
        ;;
    "draft:")
        emoji=":construction:"
        ;;
    "style:")
        emoji=":lipstick:"
        ;;
    "fix:")
        emoji=":bug:"
        ;;
    "chore:")
        emoji=":rainbow:"
        ;;
    *)
        echo "The specified prefix is undefined.";
		exit 0
		;;
esac

message="$emoji$prefix"
sed -i "s/$prefix/$message/" $COMMIT_MSG

exit 0